spring:
  application:
    name: mscloudgateway
  profiles:
    active: local  #com esse comando eu informo pro compilador qual arquivo de application usar
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #habilitei o localizador de microservicos e vou localizar por caixa baixa
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_SERVER}:${KEYCLOAK_PORT}/realms/mscourserealm
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://cursoms-eureka-user:ecok-usr-eeuramssur@${EUREKA_SERVER}:8761/eureka #http://user:senha@....
